baseURL = "https://teaching.wence.uk/phys52015/"
languageCode = "en-us"
title = "PHYS52015 – Introduction to Scientific and High-Performance Computing"

staticDir = ["static"]
disablePathToLower = false
enableGitInfo = false
enableRobotsTXT = true

theme = "book"

disableKinds = ['taxonomy', 'taxonomyTerm']
# Needed for mermaid/katex shortcodes
[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokailight"
    tabWidth = 8
    
[params]
BookSection = '/'
BookSearch = false
BookComments = false
